// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG2jpCNFxNLpg5Q7DW4G18y-TRsbU6UEU',
    appId: '1:690399863458:web:69ad14e7b85967bdbdedfb',
    messagingSenderId: '690399863458',
    projectId: 'apiflutter-8e7f6',
    authDomain: 'apiflutter-8e7f6.firebaseapp.com',
    storageBucket: 'apiflutter-8e7f6.appspot.com',
    measurementId: 'G-H6ZD02DPTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXByR0SiyIM0Q6B8MC_eYqaEWSESLoiNw',
    appId: '1:690399863458:android:c0a427395c92753dbdedfb',
    messagingSenderId: '690399863458',
    projectId: 'apiflutter-8e7f6',
    storageBucket: 'apiflutter-8e7f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx8F2pJjv84DppyPQ8IvAx-5tUX0jkTGQ',
    appId: '1:690399863458:ios:a963c660da137633bdedfb',
    messagingSenderId: '690399863458',
    projectId: 'apiflutter-8e7f6',
    storageBucket: 'apiflutter-8e7f6.appspot.com',
    iosBundleId: 'com.example.apiflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx8F2pJjv84DppyPQ8IvAx-5tUX0jkTGQ',
    appId: '1:690399863458:ios:a963c660da137633bdedfb',
    messagingSenderId: '690399863458',
    projectId: 'apiflutter-8e7f6',
    storageBucket: 'apiflutter-8e7f6.appspot.com',
    iosBundleId: 'com.example.apiflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG2jpCNFxNLpg5Q7DW4G18y-TRsbU6UEU',
    appId: '1:690399863458:web:2023579dc6fcf50fbdedfb',
    messagingSenderId: '690399863458',
    projectId: 'apiflutter-8e7f6',
    authDomain: 'apiflutter-8e7f6.firebaseapp.com',
    storageBucket: 'apiflutter-8e7f6.appspot.com',
    measurementId: 'G-HWG46NT6ZR',
  );
}
